In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import seaborn as sb

In [2]:
data = pd.read_csv('Preprocessed_data.csv')
data.head()


specific_disorder  AB.A.delta.a.FP1  AB.A.delta.b.FP2  AB.A.delta.c.F7  \
0                  0         12.159137         13.113503         9.031007   
1                  0         12.404484          9.737819        13.925651   
2                  0         16.573145         15.586708        14.094928   
3                  0         26.650019         22.823161        17.942133   
4                  0         14.624474         14.277301        11.099375   

   AB.A.delta.d.F3  AB.A.delta.e.Fz  AB.A.delta.f.F4  AB.A.delta.g.F8  \
0        14.879389        15.834830        19.595759        11.605911   
1        12.325169        15.130696        10.292518        10.263299   
2        12.660197        12.979617        10.611797         8.802664   
3        17.148214        15.338128        14.571966         7.983127   
4        16.047926        17.851932        17.165379        11.682990   

   AB.A.delta.h.T3  AB.A.delta.i.C3  ...  COH.F.gamma.o.Pz.p.P4  \
0         6.084709        13.159062  ...              65.408894   
1        11.451697        10.243151  ...              84.366954   
2         7.509552         9.903838  ...              62.681353   
3        28.158009        12.027862  ...              86.582363   
4         6.193040        11.650681  ...              85.309981   

   COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  COH.F.gamma.o.Pz.s.O2  \
0              59.590594              77.310851              75.280467   
1              53.402639              60.535899              73.838548   
2              20.062716              36.041763              36.436509   
3              83.045735              85.752150              85.875624   
4              58.218838              61.211830              65.038486   

   COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  COH.F.gamma.p.P4.s.O2  \
0              57.311188              48.015594              59.579033   
1              72.298636              43.330485              71.298037   
2              47.491240              20.875426              53.747615   
3              86.286859              79.520327              84.541455   
4              76.899037              49.849540              71.791429   

   COH.F.gamma.q.T6.r.O1  COH.F.gamma.q.T6.s.O2  COH.F.gamma.r.O1.s.O2  
0              68.503920              82.885151              86.986191  
1              23.109295              62.098128              67.749204  
2               8.009907              50.202188              33.647889  
3              82.452224              86.950905              87.384296  
4              39.910653              82.739819              62.285969  

[5 rows x 1141 columns]

In [3]:
features=data.to_numpy()
features

array([[ 0.      , 12.159137, 13.113503, ..., 68.50392 , 82.885151,
        86.986191],
       [ 0.      , 12.404484,  9.737819, ..., 23.109295, 62.098128,
        67.749204],
       [ 0.      , 16.573145, 15.586708, ...,  8.009907, 50.202188,
        33.647889],
       ...,
       [ 1.      , 28.781317, 32.36923 , ...,  7.045821, 41.962451,
        19.092111],
       [ 1.      , 19.9291  , 25.196375, ..., 27.1765  , 27.529522,
        20.028446],
       [ 1.      , 65.195346, 69.241972, ..., 47.810386, 80.166825,
        64.380273]])

# **Depressed & Healthy**

In [4]:
depressed=data[data['specific_disorder']==0]
healthy=data[data['specific_disorder'].isin([1])]

In [5]:
depressed

specific_disorder  AB.A.delta.a.FP1  AB.A.delta.b.FP2  AB.A.delta.c.F7  \
0                    0         12.159137         13.113503         9.031007   
1                    0         12.404484          9.737819        13.925651   
2                    0         16.573145         15.586708        14.094928   
3                    0         26.650019         22.823161        17.942133   
4                    0         14.624474         14.277301        11.099375   
..                 ...               ...               ...              ...   
262                  0         11.130033         11.060900        10.910743   
263                  0         16.044894         16.392419        10.209064   
264                  0         28.857343         24.268564        22.296547   
265                  0         64.531704         44.681076        36.300530   
266                  0         12.121829         12.227183        11.349530   

     AB.A.delta.d.F3  AB.A.delta.e.Fz  AB.A.delta.f.F4  AB.A.delta.g.F8  \
0          14.879389        15.834830        19.595759        11.605911   
1          12.325169        15.130696        10.292518        10.263299   
2          12.660197        12.979617        10.611797         8.802664   
3          17.148214        15.338128        14.571966         7.983127   
4          16.047926        17.851932        17.165379        11.682990   
..               ...              ...              ...              ...   
262        10.985136         9.913169         9.801100         9.874427   
263        16.581262        19.036677        17.030035        17.061728   
264        26.631643        25.133965        16.817677        16.216577   
265        41.511981        44.243138        44.189076        47.241151   
266        15.210635        27.417890        15.770951        11.266677   

     AB.A.delta.h.T3  AB.A.delta.i.C3  ...  COH.F.gamma.o.Pz.p.P4  \
0           6.084709        13.159062  ...              65.408894   
1          11.451697        10.243151  ...              84.366954   
2           7.509552         9.903838  ...              62.681353   
3          28.158009        12.027862  ...              86.582363   
4           6.193040        11.650681  ...              85.309981   
..               ...              ...  ...                    ...   
262         6.597482        10.066722  ...              99.532308   
263         6.284461        16.760425  ...              99.425796   
264        13.205022        16.792526  ...              81.372567   
265        38.259374        38.777695  ...              75.445595   
266         7.958363        14.146799  ...              89.784869   

     COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  COH.F.gamma.o.Pz.s.O2  \
0                59.590594              77.310851              75.280467   
1                53.402639              60.535899              73.838548   
2                20.062716              36.041763              36.436509   
3                83.045735              85.752150              85.875624   
4                58.218838              61.211830              65.038486   
..                     ...                    ...                    ...   
262              87.937696              74.922179              97.357071   
263              82.000262              78.591106              82.354103   
264              55.053131              72.998823              81.337044   
265              74.890539              43.522219              58.702405   
266              79.208841              65.241715              76.501596   

     COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  COH.F.gamma.p.P4.s.O2  \
0                57.311188              48.015594              59.579033   
1                72.298636              43.330485              71.298037   
2                47.491240              20.875426              53.747615   
3                86.286859              79.520327              84.541455   
4                76.899037       

In [6]:
test_depressed = depressed.iloc[120:160, :]
#test_depressed.head()
train_depressed = depressed[~depressed.isin(test_depressed)].dropna(how = 'all')
train_depressed

specific_disorder  AB.A.delta.a.FP1  AB.A.delta.b.FP2  AB.A.delta.c.F7  \
0                  0.0         12.159137         13.113503         9.031007   
1                  0.0         12.404484          9.737819        13.925651   
2                  0.0         16.573145         15.586708        14.094928   
3                  0.0         26.650019         22.823161        17.942133   
4                  0.0         14.624474         14.277301        11.099375   
..                 ...               ...               ...              ...   
262                0.0         11.130033         11.060900        10.910743   
263                0.0         16.044894         16.392419        10.209064   
264                0.0         28.857343         24.268564        22.296547   
265                0.0         64.531704         44.681076        36.300530   
266                0.0         12.121829         12.227183        11.349530   

     AB.A.delta.d.F3  AB.A.delta.e.Fz  AB.A.delta.f.F4  AB.A.delta.g.F8  \
0          14.879389        15.834830        19.595759        11.605911   
1          12.325169        15.130696        10.292518        10.263299   
2          12.660197        12.979617        10.611797         8.802664   
3          17.148214        15.338128        14.571966         7.983127   
4          16.047926        17.851932        17.165379        11.682990   
..               ...              ...              ...              ...   
262        10.985136         9.913169         9.801100         9.874427   
263        16.581262        19.036677        17.030035        17.061728   
264        26.631643        25.133965        16.817677        16.216577   
265        41.511981        44.243138        44.189076        47.241151   
266        15.210635        27.417890        15.770951        11.266677   

     AB.A.delta.h.T3  AB.A.delta.i.C3  ...  COH.F.gamma.o.Pz.p.P4  \
0           6.084709        13.159062  ...              65.408894   
1          11.451697        10.243151  ...              84.366954   
2           7.509552         9.903838  ...              62.681353   
3          28.158009        12.027862  ...              86.582363   
4           6.193040        11.650681  ...              85.309981   
..               ...              ...  ...                    ...   
262         6.597482        10.066722  ...              99.532308   
263         6.284461        16.760425  ...              99.425796   
264        13.205022        16.792526  ...              81.372567   
265        38.259374        38.777695  ...              75.445595   
266         7.958363        14.146799  ...              89.784869   

     COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  COH.F.gamma.o.Pz.s.O2  \
0                59.590594              77.310851              75.280467   
1                53.402639              60.535899              73.838548   
2                20.062716              36.041763              36.436509   
3                83.045735              85.752150              85.875624   
4                58.218838              61.211830              65.038486   
..                     ...                    ...                    ...   
262              87.937696              74.922179              97.357071   
263              82.000262              78.591106              82.354103   
264              55.053131              72.998823              81.337044   
265              74.890539              43.522219              58.702405   
266              79.208841              65.241715              76.501596   

     COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  COH.F.gamma.p.P4.s.O2  \
0                57.311188              48.015594              59.579033   
1                72.298636              43.330485              71.298037   
2                47.491240              20.875426              53.747615   
3                86.286859              79.520327              84.541455   
4                76.899037       

In [7]:
test_healthy = healthy.iloc[57:76, :]
#test_depressed.head()
train_healthy = healthy[~healthy.isin(test_healthy)].dropna(how = 'all')
train_healthy

specific_disorder  AB.A.delta.a.FP1  AB.A.delta.b.FP2  AB.A.delta.c.F7  \
24                 1.0         72.431249         69.386059        62.775437   
25                 1.0         19.579138         19.703305        23.000027   
26                 1.0         17.916294         22.911557        19.951421   
27                 1.0         20.081892         17.928614        15.977752   
28                 1.0         18.429434         26.156602        15.751990   
..                 ...               ...               ...              ...   
289                1.0         41.851823         36.771496        43.671792   
290                1.0         18.986856         19.401387        27.586436   
291                1.0         28.781317         32.369230        11.717778   
292                1.0         19.929100         25.196375        14.445391   
293                1.0         65.195346         69.241972        35.361363   

     AB.A.delta.d.F3  AB.A.delta.e.Fz  AB.A.delta.f.F4  AB.A.delta.g.F8  \
24         69.193931        69.447900        69.042085        57.324333   
25         31.034078        22.461115        23.616729        50.770251   
26         16.835759        16.792161        16.887329        27.237218   
27         18.119963        17.029861        13.545934        11.612536   
28         21.654509        26.128217        26.002065        16.649180   
..               ...              ...              ...              ...   
289        36.860889        24.732236        23.607823        23.288260   
290        20.194732        19.407491        20.216570        16.465027   
291        23.134370        26.209302        25.484497        22.586688   
292        16.453456        16.590649        16.007279        18.909188   
293        28.089348        35.475808        36.804968        69.071230   

     AB.A.delta.h.T3  AB.A.delta.i.C3  ...  COH.F.gamma.o.Pz.p.P4  \
24         41.658465        55.851042  ...              78.997160   
25         14.458573        13.843582  ...              67.123295   
26         10.324034        16.298826  ...              92.844007   
27         13.578299        13.790407  ...              99.447826   
28          7.972443        24.789548  ...              79.946089   
..               ...              ...  ...                    ...   
289         7.520642        17.636528  ...              82.905657   
290        13.178851        12.687296  ...              65.917918   
291        11.368466        21.799254  ...              61.040959   
292        13.438102        17.442777  ...              99.113664   
293         6.905352        22.623165  ...              78.600293   

     COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  COH.F.gamma.o.Pz.s.O2  \
24               67.622353              70.376986              66.281673   
25               38.645146              47.996626              48.602407   
26               81.673530              78.755278              83.905221   
27               99.424714              44.181841              61.683927   
28               72.771884              64.189258              69.407868   
..                     ...                    ...                    ...   
289              34.850706              63.970519              63.982003   
290              66.700117              44.756285              49.787513   
291              27.632209              45.552852              33.638817   
292              48.328934              41.248470              28.192238   
293              68.255430              70.687410              74.433908   

     COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  COH.F.gamma.p.P4.s.O2  \
24               82.552243              57.823441              69.899527   
25               66.139329              40.072587              62.466377   
26               87.903450              75.363909              85.757201   
27               99.513428              43.007308              62.525177   
28               61.586105       

In [8]:
train_all=pd.concat([train_depressed,train_healthy])

In [9]:
test_all=pd.concat([test_depressed,test_healthy])

In [10]:
y_train=train_all['specific_disorder']
x_train=train_all.drop('specific_disorder', axis=1)

In [11]:
x_train

AB.A.delta.a.FP1  AB.A.delta.b.FP2  AB.A.delta.c.F7  AB.A.delta.d.F3  \
0           12.159137         13.113503         9.031007        14.879389   
1           12.404484          9.737819        13.925651        12.325169   
2           16.573145         15.586708        14.094928        12.660197   
3           26.650019         22.823161        17.942133        17.148214   
4           14.624474         14.277301        11.099375        16.047926   
..                ...               ...              ...              ...   
289         41.851823         36.771496        43.671792        36.860889   
290         18.986856         19.401387        27.586436        20.194732   
291         28.781317         32.369230        11.717778        23.134370   
292         19.929100         25.196375        14.445391        16.453456   
293         65.195346         69.241972        35.361363        28.089348   

     AB.A.delta.e.Fz  AB.A.delta.f.F4  AB.A.delta.g.F8  AB.A.delta.h.T3  \
0          15.834830        19.595759        11.605911         6.084709   
1          15.130696        10.292518        10.263299        11.451697   
2          12.979617        10.611797         8.802664         7.509552   
3          15.338128        14.571966         7.983127        28.158009   
4          17.851932        17.165379        11.682990         6.193040   
..               ...              ...              ...              ...   
289        24.732236        23.607823        23.288260         7.520642   
290        19.407491        20.216570        16.465027        13.178851   
291        26.209302        25.484497        22.586688        11.368466   
292        16.590649        16.007279        18.909188        13.438102   
293        35.475808        36.804968        69.071230         6.905352   

     AB.A.delta.i.C3  AB.A.delta.j.Cz  ...  COH.F.gamma.o.Pz.p.P4  \
0          13.159062        16.848773  ...              65.408894   
1          10.243151        12.190106  ...              84.366954   
2           9.903838        11.403198  ...              62.681353   
3          12.027862        14.318378  ...              86.582363   
4          11.650681        12.666438  ...              85.309981   
..               ...              ...  ...                    ...   
289        17.636528        20.220791  ...              82.905657   
290        12.687296        20.257619  ...              65.917918   
291        21.799254        36.083181  ...              61.040959   
292        17.442777        18.859586  ...              99.113664   
293        22.623165        31.587806  ...              78.600293   

     COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  COH.F.gamma.o.Pz.s.O2  \
0                59.590594              77.310851              75.280467   
1                53.402639              60.535899              73.838548   
2                20.062716              36.041763              36.436509   
3                83.045735              85.752150              85.875624   
4                58.218838              61.211830              65.038486   
..                     ...                    ...                    ...   
289              34.850706              63.970519              63.982003   
290              66.700117              44.756285              49.787513   
291              27.632209              45.552852              33.638817   
292              48.328934              41.248470              28.192238   
293              68.255430              70.687410              74.433908   

     COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  COH.F.gamma.p.P4.s.O2  \
0                57.311188              48.015594              59.579033   
1                72.298636              43.330485              71.298037   
2                47.491240              20.875426              53.747615   
3                86.286859              79.520327              84.541455   
4                76.899037              49.849540        

In [12]:
y_test=test_all['specific_disorder']
x_test=test_all.drop('specific_disorder', axis=1)

In [13]:
y_test

188    0
189    0
190    0
191    0
192    0
193    0
194    0
195    0
196    0
197    0
198    0
199    0
200    0
201    0
202    0
203    0
204    0
205    0
206    0
207    0
208    0
209    0
210    0
211    0
212    0
213    0
214    0
215    0
216    0
217    0
218    0
219    0
220    0
221    0
222    0
223    0
224    0
225    0
226    0
227    0
81     1
82     1
83     1
84     1
85     1
86     1
87     1
88     1
89     1
90     1
91     1
267    1
268    1
269    1
270    1
271    1
272    1
273    1
274    1
Name: specific_disorder, dtype: int64

In [14]:
y_train

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
289    1.0
290    1.0
291    1.0
292    1.0
293    1.0
Name: specific_disorder, Length: 235, dtype: float64

In [15]:
x_test

AB.A.delta.a.FP1  AB.A.delta.b.FP2  AB.A.delta.c.F7  AB.A.delta.d.F3  \
188         16.152137         15.639342        13.459969        13.756504   
189         19.947162         17.838251        12.817990        12.692273   
190         16.672351         16.090772        16.515193        15.074318   
191         27.363120         32.154138        21.623961        30.771994   
192         18.679147         12.558433        15.141028        39.421597   
193         13.694119         12.529479         6.745564         9.606009   
194         25.483437         26.971285        35.581333        34.785765   
195         29.642496         28.419546        17.259390        14.423154   
196         59.302431         73.998810        55.186133        62.616810   
197         21.692226         16.547974        19.205923        27.088905   
198         10.304220         11.524545         9.936073        11.793999   
199         11.311594         11.563585        11.154134        13.992530   
200         23.601305         23.529930        15.988727        21.139251   
201         10.832542         10.199648         9.559642        10.410307   
202         12.026561         12.514910         8.658979        11.312741   
203         15.827831         13.138966        15.764484        12.409445   
204         13.263211         40.116647        13.003357        13.346887   
205         27.667328         32.015942        22.090494        31.669160   
206         21.839498          8.969227        15.376159        34.274484   
207         13.540613         13.771226        13.626981        10.119399   
208         15.253006         19.427968        15.463780        13.905269   
209         34.281846         37.138937        31.686438        29.922188   
210         11.446862         11.694065        13.902398        10.731917   
211         31.588461         11.950260        10.043504        13.484860   
212         23.125968         22.474337        22.672447        35.183755   
213         17.407522         17.548326        26.833277        19.002854   
214         37.714787        101.515687        19.423038        31.963712   
215         23.780399         24.609222        19.974207        19.651808   
216         19.737040         32.181240        42.567690        15.967456   
217          8.156584          9.568175        18.063783         8.221623   
218          9.302777          9.508905         9.520983        12.854360   
219         17.675221         29.523084        17.655832        17.817479   
220         36.465761         30.552808        35.948799        35.756381   
221         13.275519         24.337558        12.318615        18.286454   
222         22.425907         44.437950        31.148042        37.908099   
223          7.323780          5.546099         6.531624        10.814031   
224         15.079281         16.058012        13.882457        16.769271   
225         34.624061         29.011331        29.624525        21.093993   
226         15.216377         61.817752         8.429904        13.730059   
227         38.500897         28.024428        26.191677        32.251423   
81          15.883448         14.867202        11.412712        15.789144   
82          10.882066         10.877931         9.693268        11.068271   
83          10.882066         10.877931         9.693268        11.068271   
84          14.052028         15.154896         9.838617        17.327205   
85          10.557399         10.640725         8.103579        13.268817   
86          10.128482         10.143076         8.786359         9.836045   
87           8.913465          9.395801         7.274351        12.292658   
88          16.006700         15.803780        15.904397        18.645839   
89           8.467309          9.222580         7.485168         8.359260   
90          17.509894         20.817503        14.148675        17.395748   
91          25.998395         24.051959        12.284372        18.925978   
2

In [16]:
x_train_smt = x_train 
x_test_smt = x_test
y_train_smt = y_train 
y_test_smt  = y_test

In [17]:
algorithm_names = []
accuracies = []
Sensitivity = []
FPRs = []
cohen_kappas = []
auc_scores = []

# SVM

In [18]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
modelSVC = SVC(probability=True)
modelSVC.fit(x_train_smt, y_train_smt)
print(modelSVC.score(x_test_smt, y_test_smt))

y_pred = modelSVC.predict(x_test_smt)
y_final = y_test
y_pred_svc = y_pred
ac = accuracy_score(y_test_smt, y_pred)
print(ac)

0.7288135593220338
0.7288135593220338


In [19]:
# Performance Measure of SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelSVC.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[40  0]
 [16  3]]
              precision    recall  f1-score   support

           0       0.71      1.00      0.83        40
           1       1.00      0.16      0.27        19

    accuracy                           0.73        59
   macro avg       0.86      0.58      0.55        59
weighted avg       0.81      0.73      0.65        59



In [20]:
from sklearn.metrics import cohen_kappa_score
cmSVC = confusion_matrix(y_test_smt, modelSVC.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmSVC[1,1]  
TN = cmSVC[0,0] 
FP = cmSVC[0,1] 
FN = cmSVC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
totalSVC=sum(sum(cmSVC))
Accuracy = (TN+TP)/totalSVC
# MCC
val = (TP * TN) - (FP * FN)
MCC_SVC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelSVC.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_SVC))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.15789473684210525
FPR: 0.0
Specificity/TNR: 1.0
MCC: 0.33583024712973375
Cohen Kappa: 0.20270270270270285


In [21]:
# AUC Score
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelSVC.predict_proba(x_test_smt)
pred_prob2 = modelSVC.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.7934210526315789 0.7934210526315789


In [22]:
# Support Vector Classifier K - Fold CV
from sklearn.model_selection import cross_val_score
cv_score_for_SVC = cross_val_score(modelSVC, x_train_smt, y_train_smt, cv = 10)
cv_score_for_SVC

array([0.70833333, 0.625     , 0.625     , 0.66666667, 0.66666667,
       0.69565217, 0.69565217, 0.73913043, 0.69565217, 0.65217391])

In [23]:
from statistics import mean
print('Accuracy mean and std : %.3f (%.3f)' % (mean(cv_score_for_SVC), np.std(cv_score_for_SVC)))

Accuracy mean and std : 0.677 (0.035)


In [24]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelSVC.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[40  0]
 [16  3]]
              precision    recall  f1-score   support

           0       0.71      1.00      0.83        40
           1       1.00      0.16      0.27        19

    accuracy                           0.73        59
   macro avg       0.86      0.58      0.55        59
weighted avg       0.81      0.73      0.65        59



## Performance Matrix of SVM

In [25]:
algorithm_names.append('SVM')
accuracies.append(ac)
Sensitivity.append(TPR)
FPRs.append(FPR)
cohen_kappas.append(cohen_score)
auc_scores.append(auc_score1)

# Decision Tree Classifier Train, Test

In [26]:
from sklearn import tree
from sklearn.metrics import accuracy_score


modelDTC = tree.DecisionTreeClassifier(max_depth=19, min_samples_leaf=9, min_samples_split=10)
modelDTC.fit(x_train_smt, y_train_smt)
print(modelDTC.score(x_test_smt, y_test_smt))

# Predicting the Test set results
y_pred = modelDTC.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)
print(ac)

0.6779661016949152
0.6779661016949152


In [27]:
# Performance Measure of DTC

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelDTC.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[32  8]
 [11  8]]
              precision    recall  f1-score   support

           0       0.74      0.80      0.77        40
           1       0.50      0.42      0.46        19

    accuracy                           0.68        59
   macro avg       0.62      0.61      0.61        59
weighted avg       0.67      0.68      0.67        59



In [28]:
from sklearn.metrics import cohen_kappa_score
cmDTC = confusion_matrix(y_test_smt, modelDTC.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmDTC[1,1]  
TN = cmDTC[0,0] 
FP = cmDTC[0,1] 
FN = cmDTC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalDTC=sum(sum(cmDTC))
Accuracy = (TN+TP)/totalDTC
# MCC
val = (TP * TN) - (FP * FN)
MCC_DTC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelDTC.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_DTC))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.42105263157894735
FPR: 0.2
Specificity/TNR: 0.8
MCC: 0.23233159099927542
Cohen Kappa: 0.23061084420041178


In [29]:
#AUC Score
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelDTC.predict_proba(x_test_smt)
pred_prob2 = modelDTC.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.6282894736842105 0.6282894736842105


In [30]:
# Decision Tree Classifier K - Fold CV
from sklearn.model_selection import cross_val_score
cv_score_for_DTC = cross_val_score(modelDTC, x_train_smt, y_train_smt, cv = 10)
cv_score_for_DTC

array([0.66666667, 0.58333333, 0.54166667, 0.66666667, 0.75      ,
       0.69565217, 0.60869565, 0.7826087 , 0.7826087 , 0.47826087])

In [31]:
print('Accuracy mean and std : %.3f (%.3f)' % (np.mean(cv_score_for_DTC), np.std(cv_score_for_DTC)))

Accuracy mean and std : 0.656 (0.097)


## Performance Matrix of Decision Tree Classifier

In [32]:
algorithm_names.append('DTC')
accuracies.append(ac)
Sensitivity.append(TPR)
FPRs.append(FPR)
cohen_kappas.append(cohen_score)
auc_scores.append(auc_score1)

# Random Forest Training and Testing

In [55]:
from sklearn import ensemble
from sklearn.metrics import accuracy_score

modelRFC = ensemble.RandomForestClassifier(n_estimators = 10)
modelRFC.fit(x_train_smt, y_train_smt)
print(modelRFC.score(x_test_smt, y_test_smt))


# Predicting the Test set results
y_pred = modelRFC.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)

y_pred_rf = y_pred
print(ac)

0.7457627118644068
0.7457627118644068


In [56]:
# Performance Measure of RFC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelRFC.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[39  1]
 [14  5]]
              precision    recall  f1-score   support

           0       0.74      0.97      0.84        40
           1       0.83      0.26      0.40        19

    accuracy                           0.75        59
   macro avg       0.78      0.62      0.62        59
weighted avg       0.77      0.75      0.70        59



In [57]:
from sklearn.metrics import cohen_kappa_score
cmRFC = confusion_matrix(y_test_smt, modelRFC.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmRFC[1,1]  
TN = cmRFC[0,0] 
FP = cmRFC[0,1] 
FN = cmRFC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalRFC=sum(sum(cmRFC))
Accuracy = (TN+TP)/totalRFC
# MCC
val = (TP * TN) - (FP * FN)
MCC_RFC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelRFC.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_RFC))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.2631578947368421
FPR: 0.025
Specificity/TNR: 0.975
MCC: 0.368178325962713
Cohen Kappa: 0.2902967121090617


In [58]:
#AUC Score
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelRFC.predict_proba(x_test_smt)
pred_prob2 = modelRFC.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.7539473684210526 0.7539473684210526


In [59]:
# Random Forest Classifier K - Fold CV
from sklearn.model_selection import cross_val_score
cv_score_for_RFC = cross_val_score(modelRFC, x_train_smt, y_train_smt, cv = 10)
cv_score_for_RFC

array([0.66666667, 0.625     , 0.70833333, 0.58333333, 0.75      ,
       0.69565217, 0.7826087 , 0.7826087 , 0.82608696, 0.60869565])

In [38]:
print('Accuracy mean and std : %.3f (%.3f)' % (np.mean(cv_score_for_RFC), np.std(cv_score_for_RFC)))

Accuracy mean and std : 0.711 (0.058)


## Performance Matrix of Random Forrest Classifier

In [39]:
algorithm_names.append('RF')
accuracies.append(ac)
Sensitivity.append(TPR)
FPRs.append(FPR)
cohen_kappas.append(cohen_score)
auc_scores.append(auc_score1)

# Logistic Regression Train, Test

In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

modelLR = LogisticRegression()
modelLR.fit(x_train_smt, y_train_smt)
print(modelLR.score(x_test_smt, y_test_smt))


# Predicting the Test set results
y_pred = modelLR.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)
print(ac)

0.8135593220338984
0.8135593220338984


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [41]:
# Performance Measure of Logistic regression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelLR.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[37  3]
 [ 8 11]]
              precision    recall  f1-score   support

           0       0.82      0.93      0.87        40
           1       0.79      0.58      0.67        19

    accuracy                           0.81        59
   macro avg       0.80      0.75      0.77        59
weighted avg       0.81      0.81      0.80        59



In [42]:
from sklearn.metrics import cohen_kappa_score
cmLR = confusion_matrix(y_test_smt, modelLR.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmLR[1,1]  
TN = cmLR[0,0] 
FP = cmLR[0,1] 
FN = cmLR[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalLR=sum(sum(cmLR))
Accuracy = (TN+TP)/totalLR
# MCC
val = (TP * TN) - (FP * FN)
MCC_LR = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelLR.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_LR))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.5789473684210527
FPR: 0.075
Specificity/TNR: 0.925
MCC: 0.5535051972128966
Cohen Kappa: 0.5413427561837456


In [43]:
# AUC score
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelLR.predict_proba(x_test_smt)
pred_prob2 = modelLR.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.8486842105263158 0.8486842105263158


In [44]:
# Logistic Regression K-fold CV
from sklearn.model_selection import cross_val_score
cv_score_for_LR = cross_val_score(modelLR, x_train_smt, y_train_smt, cv = 10)
cv_score_for_LR

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.58333333, 0.70833333, 0.625     , 0.66666667, 0.75      ,
       0.69565217, 0.47826087, 0.73913043, 0.73913043, 0.43478261])

In [45]:
print('Accuracy mean and std : %.3f (%.3f)' % (np.mean(cv_score_for_LR), np.std(cv_score_for_LR)))

Accuracy mean and std : 0.642 (0.106)


## Performance Matrix of Logistic Regression

In [46]:
algorithm_names.append('LR')
accuracies.append(ac)
Sensitivity.append(TPR)
FPRs.append(FPR)
cohen_kappas.append(cohen_score)
auc_scores.append(auc_score1)

# KNN

In [47]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors = 5)
knn_model.fit(x_train,y_train)
y_pred = knn_model.predict(x_test)
y_pred

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 1., 0., 0., 0., 1., 0., 0.])

# Evaluation

In [48]:
from sklearn import metrics
print("Accuracy is",metrics.accuracy_score(y_test,y_pred)," when k = 3")
print("Accuracy is",metrics.accuracy_score(y_test,y_pred)," when k = 5")
print("Accuracy is",metrics.accuracy_score(y_test,y_pred)," when k = 7")

Accuracy is 0.711864406779661  when k = 3
Accuracy is 0.711864406779661  when k = 5
Accuracy is 0.711864406779661  when k = 7


In [49]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.73      0.93      0.81        40
           1       0.62      0.26      0.37        19

    accuracy                           0.71        59
   macro avg       0.68      0.59      0.59        59
weighted avg       0.69      0.71      0.67        59



## Performance Matrix of KNN Classifier

## Stacking Ensemble

In [50]:
#make a prediction with a stacking ensemble
from sklearn.datasets import make_classification
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB


# define the base models
level0 = list()
#level0.append(('lr', LogisticRegression()))  #52.8%  (but increasing the accuracy)
#level0.append(('knn', KNeighborsClassifier()))
level0.append(('cart', DecisionTreeClassifier()))  #adding it gives worst performance
#level0.append(('CB',CatBoostClassifier(iterations=500)))
level0.append(('svm', SVC()))  #58.6%
#level0.append(('xgb',xgb.XGBClassifier()))   #69.9%
level0.append(('rf', ensemble.RandomForestClassifier()))  # 72


# define meta learner model
#level1 = LogisticRegression()
level1 = ensemble.RandomForestClassifier()
# define the stacking ensemble
model = StackingClassifier(estimators=level0, final_estimator=level1, cv=10)

# fit the model on all available data
model.fit(x_train_smt, y_train_smt)

y_pred = model.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)
print('Testing',ac)
cm = confusion_matrix(y_test_smt, y_pred)
cm

Testing 0.711864406779661


array([[36,  4],
       [13,  6]], dtype=int64)

In [51]:
Performance_Matrix = {
    "Model": algorithm_names,
    "Accuracy": accuracies,
    "Sensitivity": Sensitivity,
    "FPR": FPRs,
    "Cohen's Kappa": cohen_kappas,
    "AUC": auc_scores
    # Add more key-value pairs for other metrics if needed
}

In [60]:
Performance_Matrix = pd.DataFrame(Performance_Matrix)
Performance_Matrix

Model  Accuracy  Sensitivity    FPR  Cohen's Kappa       AUC
0   SVM  0.728814     0.157895  0.000       0.202703  0.793421
1   DTC  0.677966     0.421053  0.200       0.230611  0.628289
2    RF  0.796610     0.421053  0.025       0.459542  0.800658
3    LR  0.813559     0.578947  0.075       0.541343  0.848684

# Export CSV

In [53]:
# Performance_Matrix.to_csv('4th 5-fold CV Perfomance Matrix.csv', index=False)