In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import seaborn as sb

In [56]:
data = pd.read_csv('Preprocessed_data.csv')
data.head()


specific_disorder  AB.A.delta.a.FP1  AB.A.delta.b.FP2  AB.A.delta.c.F7  \
0                  0         12.159137         13.113503         9.031007   
1                  0         12.404484          9.737819        13.925651   
2                  0         16.573145         15.586708        14.094928   
3                  0         26.650019         22.823161        17.942133   
4                  0         14.624474         14.277301        11.099375   

   AB.A.delta.d.F3  AB.A.delta.e.Fz  AB.A.delta.f.F4  AB.A.delta.g.F8  \
0        14.879389        15.834830        19.595759        11.605911   
1        12.325169        15.130696        10.292518        10.263299   
2        12.660197        12.979617        10.611797         8.802664   
3        17.148214        15.338128        14.571966         7.983127   
4        16.047926        17.851932        17.165379        11.682990   

   AB.A.delta.h.T3  AB.A.delta.i.C3  ...  COH.F.gamma.o.Pz.p.P4  \
0         6.084709        13.159062  ...              65.408894   
1        11.451697        10.243151  ...              84.366954   
2         7.509552         9.903838  ...              62.681353   
3        28.158009        12.027862  ...              86.582363   
4         6.193040        11.650681  ...              85.309981   

   COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  COH.F.gamma.o.Pz.s.O2  \
0              59.590594              77.310851              75.280467   
1              53.402639              60.535899              73.838548   
2              20.062716              36.041763              36.436509   
3              83.045735              85.752150              85.875624   
4              58.218838              61.211830              65.038486   

   COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  COH.F.gamma.p.P4.s.O2  \
0              57.311188              48.015594              59.579033   
1              72.298636              43.330485              71.298037   
2              47.491240              20.875426              53.747615   
3              86.286859              79.520327              84.541455   
4              76.899037              49.849540              71.791429   

   COH.F.gamma.q.T6.r.O1  COH.F.gamma.q.T6.s.O2  COH.F.gamma.r.O1.s.O2  
0              68.503920              82.885151              86.986191  
1              23.109295              62.098128              67.749204  
2               8.009907              50.202188              33.647889  
3              82.452224              86.950905              87.384296  
4              39.910653              82.739819              62.285969  

[5 rows x 1141 columns]

In [57]:
print(data['specific_disorder'].value_counts())

0    199
1     95
Name: specific_disorder, dtype: int64


In [58]:
features=data.to_numpy()
features

array([[ 0.      , 12.159137, 13.113503, ..., 68.50392 , 82.885151,
        86.986191],
       [ 0.      , 12.404484,  9.737819, ..., 23.109295, 62.098128,
        67.749204],
       [ 0.      , 16.573145, 15.586708, ...,  8.009907, 50.202188,
        33.647889],
       ...,
       [ 1.      , 28.781317, 32.36923 , ...,  7.045821, 41.962451,
        19.092111],
       [ 1.      , 19.9291  , 25.196375, ..., 27.1765  , 27.529522,
        20.028446],
       [ 1.      , 65.195346, 69.241972, ..., 47.810386, 80.166825,
        64.380273]])

# **Depressed & Healthy**

In [59]:
depressed=data[data['specific_disorder']==0]
healthy=data[data['specific_disorder'].isin([1])]

In [60]:
depressed

specific_disorder  AB.A.delta.a.FP1  AB.A.delta.b.FP2  AB.A.delta.c.F7  \
0                    0         12.159137         13.113503         9.031007   
1                    0         12.404484          9.737819        13.925651   
2                    0         16.573145         15.586708        14.094928   
3                    0         26.650019         22.823161        17.942133   
4                    0         14.624474         14.277301        11.099375   
..                 ...               ...               ...              ...   
262                  0         11.130033         11.060900        10.910743   
263                  0         16.044894         16.392419        10.209064   
264                  0         28.857343         24.268564        22.296547   
265                  0         64.531704         44.681076        36.300530   
266                  0         12.121829         12.227183        11.349530   

     AB.A.delta.d.F3  AB.A.delta.e.Fz  AB.A.delta.f.F4  AB.A.delta.g.F8  \
0          14.879389        15.834830        19.595759        11.605911   
1          12.325169        15.130696        10.292518        10.263299   
2          12.660197        12.979617        10.611797         8.802664   
3          17.148214        15.338128        14.571966         7.983127   
4          16.047926        17.851932        17.165379        11.682990   
..               ...              ...              ...              ...   
262        10.985136         9.913169         9.801100         9.874427   
263        16.581262        19.036677        17.030035        17.061728   
264        26.631643        25.133965        16.817677        16.216577   
265        41.511981        44.243138        44.189076        47.241151   
266        15.210635        27.417890        15.770951        11.266677   

     AB.A.delta.h.T3  AB.A.delta.i.C3  ...  COH.F.gamma.o.Pz.p.P4  \
0           6.084709        13.159062  ...              65.408894   
1          11.451697        10.243151  ...              84.366954   
2           7.509552         9.903838  ...              62.681353   
3          28.158009        12.027862  ...              86.582363   
4           6.193040        11.650681  ...              85.309981   
..               ...              ...  ...                    ...   
262         6.597482        10.066722  ...              99.532308   
263         6.284461        16.760425  ...              99.425796   
264        13.205022        16.792526  ...              81.372567   
265        38.259374        38.777695  ...              75.445595   
266         7.958363        14.146799  ...              89.784869   

     COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  COH.F.gamma.o.Pz.s.O2  \
0                59.590594              77.310851              75.280467   
1                53.402639              60.535899              73.838548   
2                20.062716              36.041763              36.436509   
3                83.045735              85.752150              85.875624   
4                58.218838              61.211830              65.038486   
..                     ...                    ...                    ...   
262              87.937696              74.922179              97.357071   
263              82.000262              78.591106              82.354103   
264              55.053131              72.998823              81.337044   
265              74.890539              43.522219              58.702405   
266              79.208841              65.241715              76.501596   

     COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  COH.F.gamma.p.P4.s.O2  \
0                57.311188              48.015594              59.579033   
1                72.298636              43.330485              71.298037   
2                47.491240              20.875426              53.747615   
3                86.286859              79.520327              84.541455   
4                76.899037       

In [61]:
test_depressed = depressed.iloc[:40, :]
#test_depressed.head()
train_depressed = depressed[~depressed.isin(test_depressed)].dropna(how = 'all')
train_depressed

specific_disorder  AB.A.delta.a.FP1  AB.A.delta.b.FP2  AB.A.delta.c.F7  \
108                0.0         11.912450         16.558191        10.783598   
109                0.0         15.492252         17.176155        10.037548   
110                0.0         17.539884         16.761818        19.421935   
111                0.0         13.070098         11.464281         9.812171   
112                0.0          9.332090          9.091157         8.653219   
..                 ...               ...               ...              ...   
262                0.0         11.130033         11.060900        10.910743   
263                0.0         16.044894         16.392419        10.209064   
264                0.0         28.857343         24.268564        22.296547   
265                0.0         64.531704         44.681076        36.300530   
266                0.0         12.121829         12.227183        11.349530   

     AB.A.delta.d.F3  AB.A.delta.e.Fz  AB.A.delta.f.F4  AB.A.delta.g.F8  \
108        18.470499        17.288106        20.241134        13.402240   
109        16.733004        25.547069        23.038821        13.171694   
110        17.178094        19.842549        21.794005        20.441016   
111        10.865231        21.438704        12.504140        10.906474   
112        10.208292        11.142373        10.302199         8.444620   
..               ...              ...              ...              ...   
262        10.985136         9.913169         9.801100         9.874427   
263        16.581262        19.036677        17.030035        17.061728   
264        26.631643        25.133965        16.817677        16.216577   
265        41.511981        44.243138        44.189076        47.241151   
266        15.210635        27.417890        15.770951        11.266677   

     AB.A.delta.h.T3  AB.A.delta.i.C3  ...  COH.F.gamma.o.Pz.p.P4  \
108         7.734058        20.695575  ...              62.757879   
109        11.583645         7.691637  ...              57.678657   
110        17.622089        13.743581  ...              47.329698   
111         8.475695        10.863127  ...              36.351812   
112         6.337573         8.828996  ...              83.385220   
..               ...              ...  ...                    ...   
262         6.597482        10.066722  ...              99.532308   
263         6.284461        16.760425  ...              99.425796   
264        13.205022        16.792526  ...              81.372567   
265        38.259374        38.777695  ...              75.445595   
266         7.958363        14.146799  ...              89.784869   

     COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  COH.F.gamma.o.Pz.s.O2  \
108              60.248634              63.248428              59.472446   
109              55.604326              30.892636              51.843081   
110              68.621897              53.229637              26.707985   
111              45.063999              41.892487              36.097611   
112              83.688981              64.717213              83.377278   
..                     ...                    ...                    ...   
262              87.937696              74.922179              97.357071   
263              82.000262              78.591106              82.354103   
264              55.053131              72.998823              81.337044   
265              74.890539              43.522219              58.702405   
266              79.208841              65.241715              76.501596   

     COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  COH.F.gamma.p.P4.s.O2  \
108              97.867221              43.152749              96.768896   
109              98.170874              20.335924              65.972726   
110              56.188653              41.588408              20.552034   
111              27.457092              23.551547              17.342384   
112              99.133832       

In [62]:
test_healthy = healthy.iloc[:19, :]
#test_depressed.head()
train_healthy = healthy[~healthy.isin(test_healthy)].dropna(how = 'all')
train_healthy

specific_disorder  AB.A.delta.a.FP1  AB.A.delta.b.FP2  AB.A.delta.c.F7  \
43                 1.0         23.143169         25.351153        17.114992   
44                 1.0         14.295208         19.365374        13.664141   
45                 1.0         11.999085         12.887885        13.979760   
46                 1.0          9.906857          8.699086         7.344513   
47                 1.0          9.799614          8.880712         8.685758   
..                 ...               ...               ...              ...   
289                1.0         41.851823         36.771496        43.671792   
290                1.0         18.986856         19.401387        27.586436   
291                1.0         28.781317         32.369230        11.717778   
292                1.0         19.929100         25.196375        14.445391   
293                1.0         65.195346         69.241972        35.361363   

     AB.A.delta.d.F3  AB.A.delta.e.Fz  AB.A.delta.f.F4  AB.A.delta.g.F8  \
43         23.952445        26.628648        23.870926        17.089745   
44         15.468479        18.357142        18.055036        18.168403   
45         12.974034        15.323421        14.590837        14.362046   
46          8.652235         9.506889        10.779065        12.478201   
47         12.193286        15.955895        12.399918         6.897792   
..               ...              ...              ...              ...   
289        36.860889        24.732236        23.607823        23.288260   
290        20.194732        19.407491        20.216570        16.465027   
291        23.134370        26.209302        25.484497        22.586688   
292        16.453456        16.590649        16.007279        18.909188   
293        28.089348        35.475808        36.804968        69.071230   

     AB.A.delta.h.T3  AB.A.delta.i.C3  ...  COH.F.gamma.o.Pz.p.P4  \
43         11.078810        19.453030  ...              76.980089   
44          7.660659        13.589427  ...              76.754373   
45         10.486399        11.513764  ...              86.858992   
46          3.684710         6.763181  ...              74.155294   
47          5.306568        12.118822  ...              89.394626   
..               ...              ...  ...                    ...   
289         7.520642        17.636528  ...              82.905657   
290        13.178851        12.687296  ...              65.917918   
291        11.368466        21.799254  ...              61.040959   
292        13.438102        17.442777  ...              99.113664   
293         6.905352        22.623165  ...              78.600293   

     COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  COH.F.gamma.o.Pz.s.O2  \
43               75.901106              67.846581              75.198098   
44               60.787442              61.770756              56.559916   
45               45.347528              13.930170              64.081231   
46               69.708513              62.032993              59.125782   
47               85.022729              87.257599              89.644831   
..                     ...                    ...                    ...   
289              34.850706              63.970519              63.982003   
290              66.700117              44.756285              49.787513   
291              27.632209              45.552852              33.638817   
292              48.328934              41.248470              28.192238   
293              68.255430              70.687410              74.433908   

     COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  COH.F.gamma.p.P4.s.O2  \
43               88.993846              62.427137              87.944599   
44               89.398661              54.693934              74.891764   
45               66.377321              15.203817              78.070716   
46               98.159831              54.169529              77.980862   
47               88.256107       

In [63]:
train_all=pd.concat([train_depressed,train_healthy])

In [64]:
test_all=pd.concat([test_depressed,test_healthy])

In [65]:
y_train=train_all['specific_disorder']
x_train=train_all.drop('specific_disorder', axis=1)

In [66]:
x_train

AB.A.delta.a.FP1  AB.A.delta.b.FP2  AB.A.delta.c.F7  AB.A.delta.d.F3  \
108         11.912450         16.558191        10.783598        18.470499   
109         15.492252         17.176155        10.037548        16.733004   
110         17.539884         16.761818        19.421935        17.178094   
111         13.070098         11.464281         9.812171        10.865231   
112          9.332090          9.091157         8.653219        10.208292   
..                ...               ...              ...              ...   
289         41.851823         36.771496        43.671792        36.860889   
290         18.986856         19.401387        27.586436        20.194732   
291         28.781317         32.369230        11.717778        23.134370   
292         19.929100         25.196375        14.445391        16.453456   
293         65.195346         69.241972        35.361363        28.089348   

     AB.A.delta.e.Fz  AB.A.delta.f.F4  AB.A.delta.g.F8  AB.A.delta.h.T3  \
108        17.288106        20.241134        13.402240         7.734058   
109        25.547069        23.038821        13.171694        11.583645   
110        19.842549        21.794005        20.441016        17.622089   
111        21.438704        12.504140        10.906474         8.475695   
112        11.142373        10.302199         8.444620         6.337573   
..               ...              ...              ...              ...   
289        24.732236        23.607823        23.288260         7.520642   
290        19.407491        20.216570        16.465027        13.178851   
291        26.209302        25.484497        22.586688        11.368466   
292        16.590649        16.007279        18.909188        13.438102   
293        35.475808        36.804968        69.071230         6.905352   

     AB.A.delta.i.C3  AB.A.delta.j.Cz  ...  COH.F.gamma.o.Pz.p.P4  \
108        20.695575        24.040341  ...              62.757879   
109         7.691637        18.840678  ...              57.678657   
110        13.743581        20.223025  ...              47.329698   
111        10.863127        14.871748  ...              36.351812   
112         8.828996        13.606197  ...              83.385220   
..               ...              ...  ...                    ...   
289        17.636528        20.220791  ...              82.905657   
290        12.687296        20.257619  ...              65.917918   
291        21.799254        36.083181  ...              61.040959   
292        17.442777        18.859586  ...              99.113664   
293        22.623165        31.587806  ...              78.600293   

     COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  COH.F.gamma.o.Pz.s.O2  \
108              60.248634              63.248428              59.472446   
109              55.604326              30.892636              51.843081   
110              68.621897              53.229637              26.707985   
111              45.063999              41.892487              36.097611   
112              83.688981              64.717213              83.377278   
..                     ...                    ...                    ...   
289              34.850706              63.970519              63.982003   
290              66.700117              44.756285              49.787513   
291              27.632209              45.552852              33.638817   
292              48.328934              41.248470              28.192238   
293              68.255430              70.687410              74.433908   

     COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  COH.F.gamma.p.P4.s.O2  \
108              97.867221              43.152749              96.768896   
109              98.170874              20.335924              65.972726   
110              56.188653              41.588408              20.552034   
111              27.457092              23.551547              17.342384   
112              99.133832              52.686256        

In [67]:
y_test=test_all['specific_disorder']
x_test=test_all.drop('specific_disorder', axis=1)

In [68]:
y_test

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
92     0
93     0
94     0
95     0
96     0
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
24     1
25     1
26     1
27     1
28     1
29     1
30     1
31     1
32     1
33     1
34     1
35     1
36     1
37     1
38     1
39     1
40     1
41     1
42     1
Name: specific_disorder, dtype: int64

In [69]:
y_train

108    0.0
109    0.0
110    0.0
111    0.0
112    0.0
      ... 
289    1.0
290    1.0
291    1.0
292    1.0
293    1.0
Name: specific_disorder, Length: 235, dtype: float64

In [70]:
x_test

AB.A.delta.a.FP1  AB.A.delta.b.FP2  AB.A.delta.c.F7  AB.A.delta.d.F3  \
0           12.159137         13.113503         9.031007        14.879389   
1           12.404484          9.737819        13.925651        12.325169   
2           16.573145         15.586708        14.094928        12.660197   
3           26.650019         22.823161        17.942133        17.148214   
4           14.624474         14.277301        11.099375        16.047926   
5           18.569593         20.765159        14.127835        20.682059   
6           28.997348         24.583036        17.184492        15.983541   
7            6.878611          5.226157         6.090039        22.464627   
8            8.727327         10.078501        13.639221         9.244833   
9           15.183242         17.575071         9.294688        11.404069   
10          32.256989         31.491901        18.104364        15.307855   
11          12.411890         10.833049        13.018176        12.137987   
12          14.958034         14.091236        13.916720        11.101946   
13          17.036455         14.028521        15.042336        18.217267   
14          19.071334         25.654394        18.926091        19.442942   
15          14.061196         15.499213         8.930149        14.065817   
16           9.174352          9.399198         7.850607         9.810458   
17          11.608491         15.257592        11.780814        14.910162   
18           7.359822          7.351615         6.168331         7.452342   
19          11.066426          9.942629        10.258901         9.609837   
20           8.189847          7.782097         7.928687        10.289899   
21          26.257840         25.081812        17.452789        29.998930   
22          47.774397         49.724859        21.166967        23.123269   
23          12.222513         12.348846        11.428976        10.707774   
92          40.948194         36.260939        24.550268        38.919360   
93          12.225732         16.201976         9.034439         8.776060   
94          17.655206         16.629363        17.583985        20.108693   
95          10.090730         10.705101         8.677492         9.369457   
96          14.425770         15.632648         9.573189        14.254269   
97          14.445573         14.719121        11.553745        12.340098   
98          24.619149         29.933954        12.565844        21.774821   
99          12.735172         16.135740        23.606439         9.448904   
100         16.698186         18.961888        15.302900        22.262750   
101         24.916521         21.988922        16.627696        21.012441   
102         17.190103         18.637210        12.000725        19.308148   
103         26.919768         24.381490        16.790731        18.541622   
104         25.397139         27.696464        19.870770        29.172495   
105         30.837102         33.554557        22.945155        26.742742   
106         13.133504         11.360428        15.969745        21.349963   
107         31.886418         31.684946        23.501583        20.696421   
24          72.431249         69.386059        62.775437        69.193931   
25          19.579138         19.703305        23.000027        31.034078   
26          17.916294         22.911557        19.951421        16.835759   
27          20.081892         17.928614        15.977752        18.119963   
28          18.429434         26.156602        15.751990        21.654509   
29          14.926786         13.648937        14.901054        18.132125   
30          10.895107         14.401242         7.360043         9.605170   
31          14.844927         14.440452        14.607437        14.543133   
32          37.450821         54.405099        24.135037        22.605822   
33          15.795989         12.389603        16.150968        13.321492   
34          32.774180         31.721541        36.373241        33.309049   
3

In [71]:
x_train_smt = x_train 
x_test_smt = x_test
y_train_smt = y_train 
y_test_smt  = y_test

In [72]:
algorithm_names = []
accuracies = []
Sensitivity = []
FPRs = []
cohen_kappas = []
auc_scores = []

# SVM

In [73]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
modelSVC = SVC(probability=True)
modelSVC.fit(x_train_smt, y_train_smt)
print(modelSVC.score(x_test_smt, y_test_smt))

y_pred = modelSVC.predict(x_test_smt)
y_final = y_test
y_pred_svc = y_pred
ac = accuracy_score(y_test_smt, y_pred)
print(ac)

0.6779661016949152
0.6779661016949152


In [74]:
# Performance Measure of SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelSVC.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[38  2]
 [17  2]]
              precision    recall  f1-score   support

           0       0.69      0.95      0.80        40
           1       0.50      0.11      0.17        19

    accuracy                           0.68        59
   macro avg       0.60      0.53      0.49        59
weighted avg       0.63      0.68      0.60        59



In [75]:
from sklearn.metrics import cohen_kappa_score
cmSVC = confusion_matrix(y_test_smt, modelSVC.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmSVC[1,1]  
TN = cmSVC[0,0] 
FP = cmSVC[0,1] 
FN = cmSVC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
totalSVC=sum(sum(cmSVC))
Accuracy = (TN+TP)/totalSVC
# MCC
val = (TP * TN) - (FP * FN)
MCC_SVC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelSVC.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_SVC))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.10526315789473684
FPR: 0.05
Specificity/TNR: 0.95
MCC: 0.10271435748934887
Cohen Kappa: 0.0697095435684647


In [76]:
# AUC Score
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelSVC.predict_proba(x_test_smt)
pred_prob2 = modelSVC.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.6197368421052631 0.6197368421052631


In [77]:
# Support Vector Classifier K - Fold CV
from sklearn.model_selection import cross_val_score
cv_score_for_SVC = cross_val_score(modelSVC, x_train_smt, y_train_smt, cv = 10)
cv_score_for_SVC

array([0.625     , 0.66666667, 0.70833333, 0.66666667, 0.66666667,
       0.7826087 , 0.73913043, 0.86956522, 0.69565217, 0.65217391])

In [78]:
from statistics import mean
print('Accuracy mean and std : %.3f (%.3f)' % (mean(cv_score_for_SVC), np.std(cv_score_for_SVC)))

Accuracy mean and std : 0.707 (0.069)


In [79]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelSVC.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[38  2]
 [17  2]]
              precision    recall  f1-score   support

           0       0.69      0.95      0.80        40
           1       0.50      0.11      0.17        19

    accuracy                           0.68        59
   macro avg       0.60      0.53      0.49        59
weighted avg       0.63      0.68      0.60        59



## Performance Matrix of SVM

In [80]:
algorithm_names.append('SVM')
accuracies.append(ac)
Sensitivity.append(TPR)
FPRs.append(FPR)
cohen_kappas.append(cohen_score)
auc_scores.append(auc_score1)

# Decision Tree Classifier Train, Test

In [81]:
from sklearn import tree
from sklearn.metrics import accuracy_score


modelDTC = tree.DecisionTreeClassifier(max_depth=19, min_samples_leaf=9, min_samples_split=10)
modelDTC.fit(x_train_smt, y_train_smt)
print(modelDTC.score(x_test_smt, y_test_smt))

# Predicting the Test set results
y_pred = modelDTC.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)
print(ac)

0.6271186440677966
0.6271186440677966


In [82]:
# Performance Measure of DTC

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelDTC.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[31  9]
 [13  6]]
              precision    recall  f1-score   support

           0       0.70      0.78      0.74        40
           1       0.40      0.32      0.35        19

    accuracy                           0.63        59
   macro avg       0.55      0.55      0.55        59
weighted avg       0.61      0.63      0.61        59



In [83]:
from sklearn.metrics import cohen_kappa_score
cmDTC = confusion_matrix(y_test_smt, modelDTC.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmDTC[1,1]  
TN = cmDTC[0,0] 
FP = cmDTC[0,1] 
FN = cmDTC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalDTC=sum(sum(cmDTC))
Accuracy = (TN+TP)/totalDTC
# MCC
val = (TP * TN) - (FP * FN)
MCC_DTC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelDTC.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_DTC))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.3157894736842105
FPR: 0.225
Specificity/TNR: 0.775
MCC: 0.09742498034004611
Cohen Kappa: 0.09610027855153203


In [84]:
#AUC Score
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelDTC.predict_proba(x_test_smt)
pred_prob2 = modelDTC.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.5710526315789474 0.5710526315789474


In [85]:
# Decision Tree Classifier K - Fold CV
from sklearn.model_selection import cross_val_score
cv_score_for_DTC = cross_val_score(modelDTC, x_train_smt, y_train_smt, cv = 10)
cv_score_for_DTC

array([0.45833333, 0.5       , 0.75      , 0.625     , 0.625     ,
       0.65217391, 0.65217391, 0.69565217, 0.82608696, 0.56521739])

In [86]:
print('Accuracy mean and std : %.3f (%.3f)' % (np.mean(cv_score_for_DTC), np.std(cv_score_for_DTC)))

Accuracy mean and std : 0.635 (0.104)


## Performance Matrix of Decision Tree Classifier

In [87]:
algorithm_names.append('DTC')
accuracies.append(ac)
Sensitivity.append(TPR)
FPRs.append(FPR)
cohen_kappas.append(cohen_score)
auc_scores.append(auc_score1)

# Random Forest Training and Testing

In [88]:
from sklearn import ensemble
from sklearn.metrics import accuracy_score

modelRFC = ensemble.RandomForestClassifier(n_estimators = 100)
modelRFC.fit(x_train_smt, y_train_smt)
print(modelRFC.score(x_test_smt, y_test_smt))


# Predicting the Test set results
y_pred = modelRFC.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)

y_pred_rf = y_pred
print(ac)

0.6779661016949152
0.6779661016949152


In [89]:
# Performance Measure of RFC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelRFC.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[37  3]
 [16  3]]
              precision    recall  f1-score   support

           0       0.70      0.93      0.80        40
           1       0.50      0.16      0.24        19

    accuracy                           0.68        59
   macro avg       0.60      0.54      0.52        59
weighted avg       0.63      0.68      0.62        59



In [90]:
from sklearn.metrics import cohen_kappa_score
cmRFC = confusion_matrix(y_test_smt, modelRFC.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmRFC[1,1]  
TN = cmRFC[0,0] 
FP = cmRFC[0,1] 
FN = cmRFC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalRFC=sum(sum(cmRFC))
Accuracy = (TN+TP)/totalRFC
# MCC
val = (TP * TN) - (FP * FN)
MCC_RFC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelRFC.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_RFC))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.15789473684210525
FPR: 0.075
Specificity/TNR: 0.925
MCC: 0.12815046704779512
Cohen Kappa: 0.10104250200481157


In [91]:
#AUC Score
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelRFC.predict_proba(x_test_smt)
pred_prob2 = modelRFC.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.6006578947368421 0.6006578947368421


In [92]:
# Random Forest Classifier K - Fold CV
from sklearn.model_selection import cross_val_score
cv_score_for_RFC = cross_val_score(modelRFC, x_train_smt, y_train_smt, cv = 10)
cv_score_for_RFC

array([0.625     , 0.66666667, 0.83333333, 0.70833333, 0.66666667,
       0.69565217, 0.82608696, 0.95652174, 0.69565217, 0.52173913])

In [93]:
print('Accuracy mean and std : %.3f (%.3f)' % (np.mean(cv_score_for_RFC), np.std(cv_score_for_RFC)))

Accuracy mean and std : 0.720 (0.116)


## Performance Matrix of Random Forrest Classifier

In [94]:
algorithm_names.append('RF')
accuracies.append(ac)
Sensitivity.append(TPR)
FPRs.append(FPR)
cohen_kappas.append(cohen_score)
auc_scores.append(auc_score1)

# Logistic Regression Train, Test

In [95]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

modelLR = LogisticRegression()
modelLR.fit(x_train_smt, y_train_smt)
print(modelLR.score(x_test_smt, y_test_smt))


# Predicting the Test set results
y_pred = modelLR.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)
print(ac)

0.6101694915254238
0.6101694915254238


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [96]:
# Performance Measure of Logistic regression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelLR.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[30 10]
 [13  6]]
              precision    recall  f1-score   support

           0       0.70      0.75      0.72        40
           1       0.38      0.32      0.34        19

    accuracy                           0.61        59
   macro avg       0.54      0.53      0.53        59
weighted avg       0.59      0.61      0.60        59



In [97]:
from sklearn.metrics import cohen_kappa_score
cmLR = confusion_matrix(y_test_smt, modelLR.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmLR[1,1]  
TN = cmLR[0,0] 
FP = cmLR[0,1] 
FN = cmLR[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalLR=sum(sum(cmLR))
Accuracy = (TN+TP)/totalLR
# MCC
val = (TP * TN) - (FP * FN)
MCC_LR = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelLR.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_LR))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.3157894736842105
FPR: 0.25
Specificity/TNR: 0.75
MCC: 0.06914630684502245
Cohen Kappa: 0.06863417982155107


In [98]:
# AUC score
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelLR.predict_proba(x_test_smt)
pred_prob2 = modelLR.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.4671052631578947 0.4671052631578947


In [99]:
# Logistic Regression K-fold CV
from sklearn.model_selection import cross_val_score
cv_score_for_LR = cross_val_score(modelLR, x_train_smt, y_train_smt, cv = 10)
cv_score_for_LR

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.5       , 0.58333333, 0.91666667, 0.75      , 0.58333333,
       0.86956522, 0.7826087 , 0.95652174, 0.7826087 , 0.47826087])

In [100]:
print('Accuracy mean and std : %.3f (%.3f)' % (np.mean(cv_score_for_LR), np.std(cv_score_for_LR)))

Accuracy mean and std : 0.720 (0.164)


## Performance Matrix of Logistic Regression

In [101]:
algorithm_names.append('LR')
accuracies.append(ac)
Sensitivity.append(TPR)
FPRs.append(FPR)
cohen_kappas.append(cohen_score)
auc_scores.append(auc_score1)

# KNN

In [102]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors = 5)
knn_model.fit(x_train,y_train)
y_pred = knn_model.predict(x_test)
y_pred

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 0., 1., 0., 0., 1.])

# Evaluation

In [103]:
from sklearn import metrics
print("Accuracy is",metrics.accuracy_score(y_test,y_pred)," when k = 3")
print("Accuracy is",metrics.accuracy_score(y_test,y_pred)," when k = 5")
print("Accuracy is",metrics.accuracy_score(y_test,y_pred)," when k = 7")

Accuracy is 0.6949152542372882  when k = 3
Accuracy is 0.6949152542372882  when k = 5
Accuracy is 0.6949152542372882  when k = 7


In [104]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.75      0.82      0.79        40
           1       0.53      0.42      0.47        19

    accuracy                           0.69        59
   macro avg       0.64      0.62      0.63        59
weighted avg       0.68      0.69      0.68        59



## Performance Matrix of KNN Classifier

# AdaBoost 


In [111]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score

modelABC = AdaBoostClassifier(random_state = 96)
modelABC.fit(x_train_smt, y_train_smt)
print(modelABC.score(x_test_smt, y_test_smt))

# Predicting the Test set results
y_pred = modelABC.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)
print(ac)

0.6271186440677966
0.6271186440677966


## Stacking Ensemble

In [110]:
#make a prediction with a stacking ensemble
from sklearn.datasets import make_classification
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB


# define the base models
level0 = list()
#level0.append(('lr', LogisticRegression()))  #52.8%  (but increasing the accuracy)
level0.append(('knn', KNeighborsClassifier()))
level0.append(('cart', DecisionTreeClassifier()))  #adding it gives worst performance
#level0.append(('CB',CatBoostClassifier(iterations=500)))
#level0.append(('svm', SVC()))  #58.6%
#level0.append(('xgb',xgb.XGBClassifier()))   #69.9%
level0.append(('rf', ensemble.RandomForestClassifier()))  # 72


# define meta learner model
#level1 = LogisticRegression()
level1 = ensemble.RandomForestClassifier()
# define the stacking ensemble
model = StackingClassifier(estimators=level0, final_estimator=level1, cv=10)

# fit the model on all available data
model.fit(x_train_smt, y_train_smt)

y_pred = model.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)
print('Testing',ac)
cm = confusion_matrix(y_test_smt, y_pred)
cm

Testing 0.6440677966101694


array([[33,  7],
       [14,  5]], dtype=int64)

In [106]:
Performance_Matrix = {
    "Model": algorithm_names,
    "Accuracy": accuracies,
    "Sensitivity": Sensitivity,
    "FPR": FPRs,
    "Cohen's Kappa": cohen_kappas,
    "AUC": auc_scores
    # Add more key-value pairs for other metrics if needed
}

In [107]:
Performance_Matrix = pd.DataFrame(Performance_Matrix)
Performance_Matrix

Model  Accuracy  Sensitivity    FPR  Cohen's Kappa       AUC
0   SVM  0.677966     0.105263  0.050       0.069710  0.619737
1   DTC  0.627119     0.315789  0.225       0.096100  0.571053
2    RF  0.677966     0.157895  0.075       0.101043  0.600658
3    LR  0.610169     0.315789  0.250       0.068634  0.467105

# Export CSV

In [108]:
# Performance_Matrix.to_csv('1st 5-fold CV Perfomance Matrix.csv', index=False)