In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import seaborn as sb

In [2]:
data = pd.read_csv('Preprocessed_data.csv')
data.head()


specific_disorder  AB.A.delta.a.FP1  AB.A.delta.b.FP2  AB.A.delta.c.F7  \
0                  0         12.159137         13.113503         9.031007   
1                  0         12.404484          9.737819        13.925651   
2                  0         16.573145         15.586708        14.094928   
3                  0         26.650019         22.823161        17.942133   
4                  0         14.624474         14.277301        11.099375   

   AB.A.delta.d.F3  AB.A.delta.e.Fz  AB.A.delta.f.F4  AB.A.delta.g.F8  \
0        14.879389        15.834830        19.595759        11.605911   
1        12.325169        15.130696        10.292518        10.263299   
2        12.660197        12.979617        10.611797         8.802664   
3        17.148214        15.338128        14.571966         7.983127   
4        16.047926        17.851932        17.165379        11.682990   

   AB.A.delta.h.T3  AB.A.delta.i.C3  ...  COH.F.gamma.o.Pz.p.P4  \
0         6.084709        13.159062  ...              65.408894   
1        11.451697        10.243151  ...              84.366954   
2         7.509552         9.903838  ...              62.681353   
3        28.158009        12.027862  ...              86.582363   
4         6.193040        11.650681  ...              85.309981   

   COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  COH.F.gamma.o.Pz.s.O2  \
0              59.590594              77.310851              75.280467   
1              53.402639              60.535899              73.838548   
2              20.062716              36.041763              36.436509   
3              83.045735              85.752150              85.875624   
4              58.218838              61.211830              65.038486   

   COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  COH.F.gamma.p.P4.s.O2  \
0              57.311188              48.015594              59.579033   
1              72.298636              43.330485              71.298037   
2              47.491240              20.875426              53.747615   
3              86.286859              79.520327              84.541455   
4              76.899037              49.849540              71.791429   

   COH.F.gamma.q.T6.r.O1  COH.F.gamma.q.T6.s.O2  COH.F.gamma.r.O1.s.O2  
0              68.503920              82.885151              86.986191  
1              23.109295              62.098128              67.749204  
2               8.009907              50.202188              33.647889  
3              82.452224              86.950905              87.384296  
4              39.910653              82.739819              62.285969  

[5 rows x 1141 columns]

In [3]:
features=data.to_numpy()
features

array([[ 0.      , 12.159137, 13.113503, ..., 68.50392 , 82.885151,
        86.986191],
       [ 0.      , 12.404484,  9.737819, ..., 23.109295, 62.098128,
        67.749204],
       [ 0.      , 16.573145, 15.586708, ...,  8.009907, 50.202188,
        33.647889],
       ...,
       [ 1.      , 28.781317, 32.36923 , ...,  7.045821, 41.962451,
        19.092111],
       [ 1.      , 19.9291  , 25.196375, ..., 27.1765  , 27.529522,
        20.028446],
       [ 1.      , 65.195346, 69.241972, ..., 47.810386, 80.166825,
        64.380273]])

# **Depressed & Healthy**

In [4]:
depressed=data[data['specific_disorder']==0]
healthy=data[data['specific_disorder'].isin([1])]

In [5]:
depressed

specific_disorder  AB.A.delta.a.FP1  AB.A.delta.b.FP2  AB.A.delta.c.F7  \
0                    0         12.159137         13.113503         9.031007   
1                    0         12.404484          9.737819        13.925651   
2                    0         16.573145         15.586708        14.094928   
3                    0         26.650019         22.823161        17.942133   
4                    0         14.624474         14.277301        11.099375   
..                 ...               ...               ...              ...   
262                  0         11.130033         11.060900        10.910743   
263                  0         16.044894         16.392419        10.209064   
264                  0         28.857343         24.268564        22.296547   
265                  0         64.531704         44.681076        36.300530   
266                  0         12.121829         12.227183        11.349530   

     AB.A.delta.d.F3  AB.A.delta.e.Fz  AB.A.delta.f.F4  AB.A.delta.g.F8  \
0          14.879389        15.834830        19.595759        11.605911   
1          12.325169        15.130696        10.292518        10.263299   
2          12.660197        12.979617        10.611797         8.802664   
3          17.148214        15.338128        14.571966         7.983127   
4          16.047926        17.851932        17.165379        11.682990   
..               ...              ...              ...              ...   
262        10.985136         9.913169         9.801100         9.874427   
263        16.581262        19.036677        17.030035        17.061728   
264        26.631643        25.133965        16.817677        16.216577   
265        41.511981        44.243138        44.189076        47.241151   
266        15.210635        27.417890        15.770951        11.266677   

     AB.A.delta.h.T3  AB.A.delta.i.C3  ...  COH.F.gamma.o.Pz.p.P4  \
0           6.084709        13.159062  ...              65.408894   
1          11.451697        10.243151  ...              84.366954   
2           7.509552         9.903838  ...              62.681353   
3          28.158009        12.027862  ...              86.582363   
4           6.193040        11.650681  ...              85.309981   
..               ...              ...  ...                    ...   
262         6.597482        10.066722  ...              99.532308   
263         6.284461        16.760425  ...              99.425796   
264        13.205022        16.792526  ...              81.372567   
265        38.259374        38.777695  ...              75.445595   
266         7.958363        14.146799  ...              89.784869   

     COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  COH.F.gamma.o.Pz.s.O2  \
0                59.590594              77.310851              75.280467   
1                53.402639              60.535899              73.838548   
2                20.062716              36.041763              36.436509   
3                83.045735              85.752150              85.875624   
4                58.218838              61.211830              65.038486   
..                     ...                    ...                    ...   
262              87.937696              74.922179              97.357071   
263              82.000262              78.591106              82.354103   
264              55.053131              72.998823              81.337044   
265              74.890539              43.522219              58.702405   
266              79.208841              65.241715              76.501596   

     COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  COH.F.gamma.p.P4.s.O2  \
0                57.311188              48.015594              59.579033   
1                72.298636              43.330485              71.298037   
2                47.491240              20.875426              53.747615   
3                86.286859              79.520327              84.541455   
4                76.899037       

In [6]:
test_depressed = depressed.iloc[160:200, :]
#test_depressed.head()
train_depressed = depressed[~depressed.isin(test_depressed)].dropna(how = 'all')
train_depressed

specific_disorder  AB.A.delta.a.FP1  AB.A.delta.b.FP2  AB.A.delta.c.F7  \
0                  0.0         12.159137         13.113503         9.031007   
1                  0.0         12.404484          9.737819        13.925651   
2                  0.0         16.573145         15.586708        14.094928   
3                  0.0         26.650019         22.823161        17.942133   
4                  0.0         14.624474         14.277301        11.099375   
..                 ...               ...               ...              ...   
223                0.0          7.323780          5.546099         6.531624   
224                0.0         15.079281         16.058012        13.882457   
225                0.0         34.624061         29.011331        29.624525   
226                0.0         15.216377         61.817752         8.429904   
227                0.0         38.500897         28.024428        26.191677   

     AB.A.delta.d.F3  AB.A.delta.e.Fz  AB.A.delta.f.F4  AB.A.delta.g.F8  \
0          14.879389        15.834830        19.595759        11.605911   
1          12.325169        15.130696        10.292518        10.263299   
2          12.660197        12.979617        10.611797         8.802664   
3          17.148214        15.338128        14.571966         7.983127   
4          16.047926        17.851932        17.165379        11.682990   
..               ...              ...              ...              ...   
223        10.814031         7.378216         6.785037         8.057728   
224        16.769271        20.307652        19.488390        12.949598   
225        21.093993        24.866288        25.665331        21.834919   
226        13.730059        18.140120        16.143948        12.083832   
227        32.251423        31.140856        28.763373        26.684860   

     AB.A.delta.h.T3  AB.A.delta.i.C3  ...  COH.F.gamma.o.Pz.p.P4  \
0           6.084709        13.159062  ...              65.408894   
1          11.451697        10.243151  ...              84.366954   
2           7.509552         9.903838  ...              62.681353   
3          28.158009        12.027862  ...              86.582363   
4           6.193040        11.650681  ...              85.309981   
..               ...              ...  ...                    ...   
223         6.491951         8.319931  ...              69.100748   
224        10.224760        14.428427  ...              78.741440   
225        15.987181        20.076824  ...              78.829541   
226         2.629827         9.011300  ...              71.890430   
227        15.854779        20.271380  ...              81.186896   

     COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  COH.F.gamma.o.Pz.s.O2  \
0                59.590594              77.310851              75.280467   
1                53.402639              60.535899              73.838548   
2                20.062716              36.041763              36.436509   
3                83.045735              85.752150              85.875624   
4                58.218838              61.211830              65.038486   
..                     ...                    ...                    ...   
223              51.717047              54.654210              65.063735   
224              56.690836              40.472987              57.974016   
225              49.330927              59.519691              47.922845   
226              52.525516              53.605072              54.863036   
227              69.634934              66.435212              75.341370   

     COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  COH.F.gamma.p.P4.s.O2  \
0                57.311188              48.015594              59.579033   
1                72.298636              43.330485              71.298037   
2                47.491240              20.875426              53.747615   
3                86.286859              79.520327              84.541455   
4                76.899037       

In [7]:
test_healthy = healthy.iloc[76:95, :]
#test_depressed.head()
train_healthy = healthy[~healthy.isin(test_healthy)].dropna(how = 'all')
train_healthy

specific_disorder  AB.A.delta.a.FP1  AB.A.delta.b.FP2  AB.A.delta.c.F7  \
24                 1.0         72.431249         69.386059        62.775437   
25                 1.0         19.579138         19.703305        23.000027   
26                 1.0         17.916294         22.911557        19.951421   
27                 1.0         20.081892         17.928614        15.977752   
28                 1.0         18.429434         26.156602        15.751990   
..                 ...               ...               ...              ...   
270                1.0          9.424917         10.973266         6.866688   
271                1.0         10.592410         16.394752        11.435845   
272                1.0         23.252767         26.389918        10.316852   
273                1.0         15.570541         14.694927        15.513418   
274                1.0          8.494820          8.282548         8.128640   

     AB.A.delta.d.F3  AB.A.delta.e.Fz  AB.A.delta.f.F4  AB.A.delta.g.F8  \
24         69.193931        69.447900        69.042085        57.324333   
25         31.034078        22.461115        23.616729        50.770251   
26         16.835759        16.792161        16.887329        27.237218   
27         18.119963        17.029861        13.545934        11.612536   
28         21.654509        26.128217        26.002065        16.649180   
..               ...              ...              ...              ...   
270        10.718820        12.813547        11.615903         9.677422   
271        17.501420        10.671049        12.009457        18.165854   
272        13.527259        14.566967        12.636206         8.691489   
273        11.000801        12.111545        11.668990        17.379516   
274        10.598264         8.302825         6.707449         6.713484   

     AB.A.delta.h.T3  AB.A.delta.i.C3  ...  COH.F.gamma.o.Pz.p.P4  \
24         41.658465        55.851042  ...              78.997160   
25         14.458573        13.843582  ...              67.123295   
26         10.324034        16.298826  ...              92.844007   
27         13.578299        13.790407  ...              99.447826   
28          7.972443        24.789548  ...              79.946089   
..               ...              ...  ...                    ...   
270         4.158677         9.808673  ...              74.892240   
271        10.880275         8.453976  ...              94.085534   
272         7.200274         9.383868  ...              69.939826   
273         5.206474         7.530846  ...              98.150551   
274         4.914745         5.621275  ...              76.055427   

     COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  COH.F.gamma.o.Pz.s.O2  \
24               67.622353              70.376986              66.281673   
25               38.645146              47.996626              48.602407   
26               81.673530              78.755278              83.905221   
27               99.424714              44.181841              61.683927   
28               72.771884              64.189258              69.407868   
..                     ...                    ...                    ...   
270              55.439504              45.991304              51.129878   
271              72.280927              70.068118              83.289060   
272              53.076596              48.357826              45.716530   
273              67.149819              34.427025              74.286847   
274              57.653819              55.004130              55.381598   

     COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  COH.F.gamma.p.P4.s.O2  \
24               82.552243              57.823441              69.899527   
25               66.139329              40.072587              62.466377   
26               87.903450              75.363909              85.757201   
27               99.513428              43.007308              62.525177   
28               61.586105       

In [8]:
train_all=pd.concat([train_depressed,train_healthy])

In [9]:
test_all=pd.concat([test_depressed,test_healthy])

In [10]:
y_train=train_all['specific_disorder']
x_train=train_all.drop('specific_disorder', axis=1)

In [11]:
x_train

AB.A.delta.a.FP1  AB.A.delta.b.FP2  AB.A.delta.c.F7  AB.A.delta.d.F3  \
0           12.159137         13.113503         9.031007        14.879389   
1           12.404484          9.737819        13.925651        12.325169   
2           16.573145         15.586708        14.094928        12.660197   
3           26.650019         22.823161        17.942133        17.148214   
4           14.624474         14.277301        11.099375        16.047926   
..                ...               ...              ...              ...   
270          9.424917         10.973266         6.866688        10.718820   
271         10.592410         16.394752        11.435845        17.501420   
272         23.252767         26.389918        10.316852        13.527259   
273         15.570541         14.694927        15.513418        11.000801   
274          8.494820          8.282548         8.128640        10.598264   

     AB.A.delta.e.Fz  AB.A.delta.f.F4  AB.A.delta.g.F8  AB.A.delta.h.T3  \
0          15.834830        19.595759        11.605911         6.084709   
1          15.130696        10.292518        10.263299        11.451697   
2          12.979617        10.611797         8.802664         7.509552   
3          15.338128        14.571966         7.983127        28.158009   
4          17.851932        17.165379        11.682990         6.193040   
..               ...              ...              ...              ...   
270        12.813547        11.615903         9.677422         4.158677   
271        10.671049        12.009457        18.165854        10.880275   
272        14.566967        12.636206         8.691489         7.200274   
273        12.111545        11.668990        17.379516         5.206474   
274         8.302825         6.707449         6.713484         4.914745   

     AB.A.delta.i.C3  AB.A.delta.j.Cz  ...  COH.F.gamma.o.Pz.p.P4  \
0          13.159062        16.848773  ...              65.408894   
1          10.243151        12.190106  ...              84.366954   
2           9.903838        11.403198  ...              62.681353   
3          12.027862        14.318378  ...              86.582363   
4          11.650681        12.666438  ...              85.309981   
..               ...              ...  ...                    ...   
270         9.808673        13.588847  ...              74.892240   
271         8.453976         9.320989  ...              94.085534   
272         9.383868        12.360881  ...              69.939826   
273         7.530846        10.205805  ...              98.150551   
274         5.621275         7.012364  ...              76.055427   

     COH.F.gamma.o.Pz.q.T6  COH.F.gamma.o.Pz.r.O1  COH.F.gamma.o.Pz.s.O2  \
0                59.590594              77.310851              75.280467   
1                53.402639              60.535899              73.838548   
2                20.062716              36.041763              36.436509   
3                83.045735              85.752150              85.875624   
4                58.218838              61.211830              65.038486   
..                     ...                    ...                    ...   
270              55.439504              45.991304              51.129878   
271              72.280927              70.068118              83.289060   
272              53.076596              48.357826              45.716530   
273              67.149819              34.427025              74.286847   
274              57.653819              55.004130              55.381598   

     COH.F.gamma.p.P4.q.T6  COH.F.gamma.p.P4.r.O1  COH.F.gamma.p.P4.s.O2  \
0                57.311188              48.015594              59.579033   
1                72.298636              43.330485              71.298037   
2                47.491240              20.875426              53.747615   
3                86.286859              79.520327              84.541455   
4                76.899037              49.849540        

In [12]:
y_test=test_all['specific_disorder']
x_test=test_all.drop('specific_disorder', axis=1)

In [13]:
y_test

228    0
229    0
230    0
231    0
232    0
233    0
234    0
235    0
236    0
237    0
238    0
239    0
240    0
241    0
242    0
243    0
244    0
245    0
246    0
247    0
248    0
249    0
250    0
251    0
252    0
253    0
254    0
255    0
256    0
257    0
258    0
259    0
260    0
261    0
262    0
263    0
264    0
265    0
266    0
275    1
276    1
277    1
278    1
279    1
280    1
281    1
282    1
283    1
284    1
285    1
286    1
287    1
288    1
289    1
290    1
291    1
292    1
293    1
Name: specific_disorder, dtype: int64

In [14]:
y_train

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
270    1.0
271    1.0
272    1.0
273    1.0
274    1.0
Name: specific_disorder, Length: 236, dtype: float64

In [15]:
x_test

AB.A.delta.a.FP1  AB.A.delta.b.FP2  AB.A.delta.c.F7  AB.A.delta.d.F3  \
228         38.397993         36.730146        30.117492        31.117358   
229         21.353704         21.941903        25.065754        17.545799   
230         18.495365         39.316120        20.799384        18.921417   
231         16.310348         18.302566        14.768880        20.782597   
232         20.289609         18.339320        18.177122        15.955673   
233         18.808291         15.814851        18.366470        18.152096   
234         37.308340         51.382485        56.604087        40.337822   
235         23.781370         24.249057        19.229832        14.064907   
236         26.830800         28.663604        19.397360        28.505741   
237         18.458634         45.735525        18.807200        27.986192   
238         46.825608         42.184530        26.166722        21.877891   
239         38.315146         36.953849        29.033028        36.502002   
240         14.201494         16.272042        12.015968        12.826417   
241         13.209028         54.030494        11.984615        13.236377   
242         13.246326         13.243722        21.909339        21.203249   
243         35.131904         30.056626        18.701098        17.881207   
244         41.012467         44.372635        22.593716        22.744269   
245         23.488215         21.986901        13.094994        18.425377   
246         19.780159         34.446030        18.297640        18.818104   
247          9.185935         12.340380         3.414780         3.412618   
248         18.624995         17.944200        19.021574        18.562730   
249         17.017981         16.206511        12.061845        12.059208   
250         26.213000         33.522821        17.110314        19.685013   
251         13.049598         13.171489        25.175026        30.211672   
252         15.120287         16.020678        14.874868        14.901294   
253          8.222372          8.277647        14.195740         8.160922   
254         14.085467         13.323170        14.989029        15.058912   
255         15.239152         11.933724        12.084029        11.601983   
256         11.807564         13.441509        10.723968        16.354037   
257         12.443379         19.703004         6.227403        10.991983   
258          9.573219         11.501388         5.035480         9.744640   
259          7.640445          7.137067         5.377288        10.506309   
260         10.831485         11.012026         7.725126        12.220781   
261          9.182671         10.919222        13.628337        10.120673   
262         11.130033         11.060900        10.910743        10.985136   
263         16.044894         16.392419        10.209064        16.581262   
264         28.857343         24.268564        22.296547        26.631643   
265         64.531704         44.681076        36.300530        41.511981   
266         12.121829         12.227183        11.349530        15.210635   
275         13.698344         14.810620        11.725193        14.849226   
276         15.808424         15.462749        10.032510        17.882107   
277         18.028682         15.598725         9.680162        15.443798   
278         16.142462         16.921597        10.640910        14.858048   
279         11.759986         11.675559        13.813623        12.371107   
280          8.142844          9.834301         6.707535         7.263691   
281         13.799266         16.881899         8.537624        10.914826   
282         16.414078         20.821382        10.722454        14.126786   
283         21.125098         23.636749         9.074053        21.613951   
284         11.712786         12.472304        10.620174        10.752794   
285         20.099558         21.491891        22.865909        18.105143   
286          6.327173          6.370860         5.350105         7.400223   
2

In [16]:
x_train_smt = x_train 
x_test_smt = x_test
y_train_smt = y_train 
y_test_smt  = y_test

In [17]:
algorithm_names = []
accuracies = []
Sensitivity = []
FPRs = []
cohen_kappas = []
auc_scores = []

# SVM

In [18]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
modelSVC = SVC(probability=True)
modelSVC.fit(x_train_smt, y_train_smt)
print(modelSVC.score(x_test_smt, y_test_smt))

y_pred = modelSVC.predict(x_test_smt)
y_final = y_test
y_pred_svc = y_pred
ac = accuracy_score(y_test_smt, y_pred)
print(ac)

0.6724137931034483
0.6724137931034483


In [19]:
# Performance Measure of SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelSVC.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[37  2]
 [17  2]]
              precision    recall  f1-score   support

           0       0.69      0.95      0.80        39
           1       0.50      0.11      0.17        19

    accuracy                           0.67        58
   macro avg       0.59      0.53      0.48        58
weighted avg       0.62      0.67      0.59        58



In [20]:
from sklearn.metrics import cohen_kappa_score
cmSVC = confusion_matrix(y_test_smt, modelSVC.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmSVC[1,1]  
TN = cmSVC[0,0] 
FP = cmSVC[0,1] 
FN = cmSVC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
totalSVC=sum(sum(cmSVC))
Accuracy = (TN+TP)/totalSVC
# MCC
val = (TP * TN) - (FP * FN)
MCC_SVC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelSVC.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_SVC))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.10526315789473684
FPR: 0.05128205128205128
Specificity/TNR: 0.9487179487179487
MCC: 0.09998250459241056
Cohen Kappa: 0.06768189509306266


In [21]:
# AUC Score
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelSVC.predict_proba(x_test_smt)
pred_prob2 = modelSVC.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.7300944669365722 0.7300944669365722


In [22]:
# Support Vector Classifier K - Fold CV
from sklearn.model_selection import cross_val_score
cv_score_for_SVC = cross_val_score(modelSVC, x_train_smt, y_train_smt, cv = 10)
cv_score_for_SVC

array([0.70833333, 0.66666667, 0.66666667, 0.66666667, 0.75      ,
       0.66666667, 0.73913043, 0.69565217, 0.7826087 , 0.69565217])

In [23]:
from statistics import mean
print('Accuracy mean and std : %.3f (%.3f)' % (mean(cv_score_for_SVC), np.std(cv_score_for_SVC)))

Accuracy mean and std : 0.704 (0.039)


In [24]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelSVC.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[37  2]
 [17  2]]
              precision    recall  f1-score   support

           0       0.69      0.95      0.80        39
           1       0.50      0.11      0.17        19

    accuracy                           0.67        58
   macro avg       0.59      0.53      0.48        58
weighted avg       0.62      0.67      0.59        58



## Performance Matrix of SVM

In [25]:
algorithm_names.append('SVM')
accuracies.append(ac)
Sensitivity.append(TPR)
FPRs.append(FPR)
cohen_kappas.append(cohen_score)
auc_scores.append(auc_score1)

# Decision Tree Classifier Train, Test

In [26]:
from sklearn import tree
from sklearn.metrics import accuracy_score


modelDTC = tree.DecisionTreeClassifier(max_depth=19, min_samples_leaf=9, min_samples_split=10)
modelDTC.fit(x_train_smt, y_train_smt)
print(modelDTC.score(x_test_smt, y_test_smt))

# Predicting the Test set results
y_pred = modelDTC.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)
print(ac)

0.603448275862069
0.603448275862069


In [27]:
# Performance Measure of DTC

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelDTC.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[30  9]
 [14  5]]
              precision    recall  f1-score   support

           0       0.68      0.77      0.72        39
           1       0.36      0.26      0.30        19

    accuracy                           0.60        58
   macro avg       0.52      0.52      0.51        58
weighted avg       0.58      0.60      0.59        58



In [28]:
from sklearn.metrics import cohen_kappa_score
cmDTC = confusion_matrix(y_test_smt, modelDTC.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmDTC[1,1]  
TN = cmDTC[0,0] 
FP = cmDTC[0,1] 
FN = cmDTC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalDTC=sum(sum(cmDTC))
Accuracy = (TN+TP)/totalDTC
# MCC
val = (TP * TN) - (FP * FN)
MCC_DTC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelDTC.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_DTC))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.2631578947368421
FPR: 0.23076923076923078
Specificity/TNR: 0.7692307692307693
MCC: 0.03552317551596569
Cohen Kappa: 0.0347322720694645


In [29]:
#AUC Score
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelDTC.predict_proba(x_test_smt)
pred_prob2 = modelDTC.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.5553306342780028 0.5553306342780028


In [30]:
# Decision Tree Classifier K - Fold CV
from sklearn.model_selection import cross_val_score
cv_score_for_DTC = cross_val_score(modelDTC, x_train_smt, y_train_smt, cv = 10)
cv_score_for_DTC

array([0.58333333, 0.625     , 0.54166667, 0.70833333, 0.79166667,
       0.75      , 0.69565217, 0.43478261, 0.56521739, 0.69565217])

In [31]:
print('Accuracy mean and std : %.3f (%.3f)' % (np.mean(cv_score_for_DTC), np.std(cv_score_for_DTC)))

Accuracy mean and std : 0.639 (0.103)


## Performance Matrix of Decision Tree Classifier

In [32]:
algorithm_names.append('DTC')
accuracies.append(ac)
Sensitivity.append(TPR)
FPRs.append(FPR)
cohen_kappas.append(cohen_score)
auc_scores.append(auc_score1)

# Random Forest Training and Testing

In [33]:
from sklearn import ensemble
from sklearn.metrics import accuracy_score

modelRFC = ensemble.RandomForestClassifier(n_estimators = 100)
modelRFC.fit(x_train_smt, y_train_smt)
print(modelRFC.score(x_test_smt, y_test_smt))


# Predicting the Test set results
y_pred = modelRFC.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)

y_pred_rf = y_pred
print(ac)

0.6379310344827587
0.6379310344827587


In [34]:
# Performance Measure of RFC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelRFC.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[32  7]
 [14  5]]
              precision    recall  f1-score   support

           0       0.70      0.82      0.75        39
           1       0.42      0.26      0.32        19

    accuracy                           0.64        58
   macro avg       0.56      0.54      0.54        58
weighted avg       0.60      0.64      0.61        58



In [35]:
from sklearn.metrics import cohen_kappa_score
cmRFC = confusion_matrix(y_test_smt, modelRFC.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmRFC[1,1]  
TN = cmRFC[0,0] 
FP = cmRFC[0,1] 
FN = cmRFC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalRFC=sum(sum(cmRFC))
Accuracy = (TN+TP)/totalRFC
# MCC
val = (TP * TN) - (FP * FN)
MCC_RFC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelRFC.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_RFC))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.2631578947368421
FPR: 0.1794871794871795
Specificity/TNR: 0.8205128205128205
MCC: 0.09694223912886053
Cohen Kappa: 0.09239940387481371


In [36]:
#AUC Score
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelRFC.predict_proba(x_test_smt)
pred_prob2 = modelRFC.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.7645074224021593 0.7645074224021593


In [37]:
# Random Forest Classifier K - Fold CV
from sklearn.model_selection import cross_val_score
cv_score_for_RFC = cross_val_score(modelRFC, x_train_smt, y_train_smt, cv = 10)
cv_score_for_RFC

array([0.66666667, 0.625     , 0.58333333, 0.75      , 0.79166667,
       0.79166667, 0.73913043, 0.65217391, 0.82608696, 0.82608696])

In [38]:
print('Accuracy mean and std : %.3f (%.3f)' % (np.mean(cv_score_for_RFC), np.std(cv_score_for_RFC)))

Accuracy mean and std : 0.725 (0.083)


## Performance Matrix of Random Forrest Classifier

In [39]:
algorithm_names.append('RF')
accuracies.append(ac)
Sensitivity.append(TPR)
FPRs.append(FPR)
cohen_kappas.append(cohen_score)
auc_scores.append(auc_score1)

# Logistic Regression Train, Test

In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

modelLR = LogisticRegression()
modelLR.fit(x_train_smt, y_train_smt)
print(modelLR.score(x_test_smt, y_test_smt))


# Predicting the Test set results
y_pred = modelLR.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)
print(ac)

0.6724137931034483
0.6724137931034483


C:\Users\babar\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [41]:
# Performance Measure of Logistic regression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelLR.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[26 13]
 [ 6 13]]
              precision    recall  f1-score   support

           0       0.81      0.67      0.73        39
           1       0.50      0.68      0.58        19

    accuracy                           0.67        58
   macro avg       0.66      0.68      0.66        58
weighted avg       0.71      0.67      0.68        58



In [42]:
from sklearn.metrics import cohen_kappa_score
cmLR = confusion_matrix(y_test_smt, modelLR.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmLR[1,1]  
TN = cmLR[0,0] 
FP = cmLR[0,1] 
FN = cmLR[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalLR=sum(sum(cmLR))
Accuracy = (TN+TP)/totalLR
# MCC
val = (TP * TN) - (FP * FN)
MCC_LR = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelLR.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_LR))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.6842105263157895
FPR: 0.3333333333333333
Specificity/TNR: 0.6666666666666666
MCC: 0.33113308926626095
Cohen Kappa: 0.3205918618988902


In [43]:
# AUC score
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelLR.predict_proba(x_test_smt)
pred_prob2 = modelLR.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.6545209176788125 0.6545209176788125


In [44]:
# Logistic Regression K-fold CV
from sklearn.model_selection import cross_val_score
cv_score_for_LR = cross_val_score(modelLR, x_train_smt, y_train_smt, cv = 10)
cv_score_for_LR

C:\Users\babar\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\babar\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.66666667, 0.66666667, 0.45833333, 0.625     , 0.83333333,
       0.875     , 0.73913043, 0.65217391, 0.7826087 , 0.7826087 ])

In [45]:
print('Accuracy mean and std : %.3f (%.3f)' % (np.mean(cv_score_for_LR), np.std(cv_score_for_LR)))

Accuracy mean and std : 0.708 (0.115)


## Performance Matrix of Logistic Regression

In [46]:
algorithm_names.append('LR')
accuracies.append(ac)
Sensitivity.append(TPR)
FPRs.append(FPR)
cohen_kappas.append(cohen_score)
auc_scores.append(auc_score1)

# KNN

In [47]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors = 5)
knn_model.fit(x_train,y_train)
y_pred = knn_model.predict(x_test)
y_pred

C:\Users\babar\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

# Evaluation

In [48]:
from sklearn import metrics
print("Accuracy is",metrics.accuracy_score(y_test,y_pred)," when k = 3")
print("Accuracy is",metrics.accuracy_score(y_test,y_pred)," when k = 5")
print("Accuracy is",metrics.accuracy_score(y_test,y_pred)," when k = 7")

Accuracy is 0.5862068965517241  when k = 3
Accuracy is 0.5862068965517241  when k = 5
Accuracy is 0.5862068965517241  when k = 7


In [49]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.65      0.82      0.73        39
           1       0.22      0.11      0.14        19

    accuracy                           0.59        58
   macro avg       0.44      0.46      0.44        58
weighted avg       0.51      0.59      0.54        58



## Performance Matrix of KNN Classifier

## Stacking Ensemble

In [50]:
#make a prediction with a stacking ensemble
from sklearn.datasets import make_classification
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB


# define the base models
level0 = list()
#level0.append(('lr', LogisticRegression()))  #52.8%  (but increasing the accuracy)
#level0.append(('knn', KNeighborsClassifier()))
level0.append(('cart', DecisionTreeClassifier()))  #adding it gives worst performance
#level0.append(('CB',CatBoostClassifier(iterations=500)))
level0.append(('svm', SVC()))  #58.6%
#level0.append(('xgb',xgb.XGBClassifier()))   #69.9%
level0.append(('rf', ensemble.RandomForestClassifier()))  # 72


# define meta learner model
#level1 = LogisticRegression()
level1 = ensemble.RandomForestClassifier()
# define the stacking ensemble
model = StackingClassifier(estimators=level0, final_estimator=level1, cv=10)

# fit the model on all available data
model.fit(x_train_smt, y_train_smt)

y_pred = model.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)
print('Testing',ac)
cm = confusion_matrix(y_test_smt, y_pred)
cm

Testing 0.603448275862069


array([[26, 13],
       [10,  9]], dtype=int64)

In [51]:
Performance_Matrix = {
    "Model": algorithm_names,
    "Accuracy": accuracies,
    "Sensitivity": Sensitivity,
    "FPR": FPRs,
    "Cohen's Kappa": cohen_kappas,
    "AUC": auc_scores
    # Add more key-value pairs for other metrics if needed
}

In [52]:
Performance_Matrix = pd.DataFrame(Performance_Matrix)
Performance_Matrix

Model  Accuracy  Sensitivity       FPR  Cohen's Kappa       AUC
0   SVM  0.672414     0.105263  0.051282       0.067682  0.730094
1   DTC  0.603448     0.263158  0.230769       0.034732  0.555331
2    RF  0.637931     0.263158  0.179487       0.092399  0.764507
3    LR  0.672414     0.684211  0.333333       0.320592  0.654521

# Export CSV

In [53]:
# Performance_Matrix.to_csv('5th 5-fold CV Perfomance Matrix.csv', index=False)